
networks:
  hs-net:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  logs_volume:
  db_data:
  letsencrypt:

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
   
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=daniel4buz@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    networks:
      - hs-net

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hs-web
    env_file: .env
    environment:
      GUNICORN_MODULE: "config.wsgi:application"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - logs_volume:/app/logs
    depends_on:
      - db
    networks:
      - hs-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hs-web.rule=HostRegexp({host:.+})"
      - "traefik.http.routers.hs-web.entrypoints=websecure"
      - "traefik.http.routers.hs-web.tls.certresolver=myresolver"
      - "traefik.http.services.hs-web.loadbalancer.server.port=8000"
      - "traefik.http.routers.hs-web-http.rule=HostRegexp({host:.+})"
      - "traefik.http.routers.hs-web-http.entrypoints=web"
      - "traefik.http.routers.hs-web-http.middlewares=https-redirect"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
  db:
    image: postgres:16
    container_name: hs-db
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - hs-net
