services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hs-web
    env_file:
      - .env
    environment:
      DATABASE_HOST: "${DATABASE_HOST:-db}"
      DATABASE_PORT: "${DATABASE_PORT:-5432}"
    volumes:
      - .:/app:cached
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - logs_volume:/app/logs
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - hs-net


  db:
    image: postgres:16
    container_name: buzio-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: "${DATABASE_NAME}"
      POSTGRES_USER: "${DATABASE_USERNAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME} -h 127.0.0.1 -p 5432 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hs-net

volumes:
  static_volume:
  media_volume:
  logs_volume:
  db_data:

networks:
  hs-net:
    driver: bridge
